### ISSUE TITLE
global name 'mean' is not defined for version 10.0

### ISSUE THREAD

**Issue by digitalliuzg** [OCA/stock-logistics-warehouse#449] opened 2018-06-21 03:21 UTC
stock_cycle_count\models\stock_location.py", line 32, in _compute_loc_accuracy
    rec.loc_accuracy = mean(
NameError: global name 'mean' is not defined

**Comment by pedrobaeza** [comment] 2018-06-21 07:16
@lreficent can you please check?

**Comment by LoisRForgeFlow** [comment] 2018-06-21 14:42
@digitalliuzg `mean` is a method from `numpy` libray. Do you have it installed? If not please run `pip install numpy`.

@pedrobaeza it is specified in the [manifest](https://github.com/OCA/stock-logistics-warehouse/blob/10.0/stock_cycle_count/__manifest__.py#L21), should I say it in the README installation section as well?

**Comment by pedrobaeza** [comment] 2018-06-21 16:11
It would be good to have it on the README, but my doubt is how can he was able to install the module then. Can it be that there's a numpy version where this method is not present?

**Comment by digitalliuzg** [comment] 2018-06-22 00:48
![image](https://user-images.githubusercontent.com/11321237/41752260-fc63191a-75f8-11e8-8c85-ec83490c19b9.png)

**Comment by LoisRForgeFlow** [comment] 2018-06-22 13:32
@digitalliuzg could you run (with the same python environment you are using for odoo) the following sentences and check that the result is the same:
```python
>>> from numpy import mean
>>> mean([1,2])
1.5
```
If  you get an error please paste it here.

**Comment by digitalliuzg** [comment] 2018-06-28 09:09
![image](https://user-images.githubusercontent.com/11321237/42024950-f7c7f586-7af5-11e8-93d6-88ca8275b51d.png)

**Comment by digitalliuzg** [comment] 2018-06-28 09:09
![image](https://user-images.githubusercontent.com/11321237/42024976-088232a6-7af6-11e8-9413-29b5e6a5abb7.png)

**Comment by digitalliuzg** [comment] 2018-06-28 09:10
![image](https://user-images.githubusercontent.com/11321237/42025001-1a8c2272-7af6-11e8-9359-cc77ba7189ae.png)

**Comment by digitalliuzg** [comment] 2018-06-29 00:39
![image](https://user-images.githubusercontent.com/11321237/42067283-fb43cbae-7b77-11e8-8880-c2d15ba94fad.png)

**Comment by digitalliuzg** [comment] 2018-06-29 00:40
![image](https://user-images.githubusercontent.com/11321237/42067304-12e29f10-7b78-11e8-80c2-c1139df1eb7d.png)

**Comment by digitalliuzg** [comment] 2018-06-29 00:45
![image](https://user-images.githubusercontent.com/11321237/42067420-b97b77ac-7b78-11e8-8039-49acae2a4110.png)

**Comment by digitalliuzg** [comment] 2018-06-29 00:47
![image](https://user-images.githubusercontent.com/11321237/42067469-fb6bcaae-7b78-11e8-9a2a-421a66cba2be.png)

**Comment by digitalliuzg** [comment] 2018-06-29 00:56
![image](https://user-images.githubusercontent.com/11321237/42067732-58dad4a4-7b7a-11e8-9ef3-5ff59c031424.png)

**Comment by digitalliuzg** [comment] 2018-06-29 01:09
![image](https://user-images.githubusercontent.com/11321237/42068017-15b8ac44-7b7c-11e8-8fd1-7d0dbbc641e0.png)

**Comment by digitalliuzg** [comment] 2018-06-29 01:17
![image](https://user-images.githubusercontent.com/11321237/42068220-4dd20a5c-7b7d-11e8-94a7-9307cf5ff8e1.png)

**Comment by digitalliuzg** [comment] 2018-06-29 01:18
![image](https://user-images.githubusercontent.com/11321237/42068235-5baba19c-7b7d-11e8-88ad-970da02e2e4a.png)

**Comment by pedrobaeza** [comment] 2018-06-29 07:25
You don't have `numpy` in your deployment environment, so this is not a problem of the module. Please learn how to get accesible the library in your environment. I think the problem is Windows, that requires to put the library manually in you Odoo folder. Any way, this is out of the scope of this issue tracker, so closing.

**Closed as completed by pedrobaeza** 2018-06-29 07:25 UTC
