### ISSUE TITLE
[10CE] module stock_put_away_product

### ISSUE THREAD

**Issue by infospa** [OCA/stock-logistics-warehouse#427] opened 2018-04-26 09:59 UTC
Hi, I have this problem, the module is perfect on the go, but I have a problem when I use the internal shift.

When I create an internal move I select the source localization zone and the destination zone - I control the reserve - the module changes the destination with the destination of the "returned" module at this point I have to return the destination otherwise the displacement does not move

If I take the destination in the product the move is ok

sorry for my bad english

**Comment by rousseldenis** [comment] 2018-04-26 10:07
@infospa Indeed, it is a little bit confusing.

Can you try to explain step by step and explain what do you mean by 'returned' module?

**Comment by infospa** [comment] 2018-04-26 13:33
Ok Scuse me!
Internal move:
![internal1](https://user-images.githubusercontent.com/38753131/39307582-8adcd3ce-4963-11e8-9c50-5307c0c1c969.PNG)

Reserve

![internal2](https://user-images.githubusercontent.com/38753131/39307831-34b60d84-4964-11e8-847b-ab439ad722b3.PNG)

If I add more products all are changed with the rules of the form

![internal3](https://user-images.githubusercontent.com/38753131/39308421-ad583b76-4965-11e8-8a83-72feabcc03ff.PNG)

I have the destination "put_away" for the product the "MODULE" changes to the automatic destination the rule "put_away", the source instead automatically takes the last selected for all products.
The 3 products instead should move all in PANDA location from the location sources assigned by the "put_away"

I hope I explained myself

I'm not sure I'm doing everything correctly if I'm wrong, correct me too

Sorry is translated by google

**Comment by infospa** [comment] 2018-04-27 09:25
Hi
Do you have news for me?

**Comment by pedrobaeza** [comment] 2018-04-27 11:14
@infospa this help is voluntary and free, so you can't demand more from the contributors. Just wait for an answer, or pay for it to the contributor you consider for getting done.

**Comment by infospa** [comment] 2018-04-27 12:13
I certainly do not want to force anyone I was just asking. ask for is reasonable answer is courtesy.
Thank you! and excuse me

**Comment by rousseldenis** [comment] 2018-05-07 09:20
@infospa Ok, I see. Reproduced on runbot.

I will look into it when I have some time to work on it.

**Comment by infospa** [comment] 2018-05-07 14:16
Ok Thank you!

**Comment by rousseldenis** [comment] 2018-05-08 09:11
@infospa This is a problem in Odoo.

I did a PR to fix that. I think you can take it and let me know if that solves your problem.

https://github.com/odoo/odoo/pull/24620

**Comment by infospa** [comment] 2018-05-08 13:34
It's ok for the internal move but when I create a sales order an error when confirm order

> 

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/sale_timesheet/models/sale_order.py", line 60, in action_confirm
    result = super(SaleOrder, self).action_confirm()
  File "/usr/lib/python2.7/site-packages/odoo/addons/sale/models/sale.py", line 458, in action_confirm
    order.order_line._action_procurement_create()
  File "/usr/lib/python2.7/site-packages/odoo/addons/procurement_jit/sale.py", line 18, in _action_procurement_create
    reassign.action_assign()
  File "/usr/lib/python2.7/site-packages/odoo/addons/stock/models/stock_picking.py", line 469, in action_assign
    moves.action_assign()
  File "/usr/lib/python2.7/site-packages/odoo/addons/stock/models/stock_move.py", line 663, in action_assign
    self.check_recompute_pack_op()
  File "/usr/lib/python2.7/site-packages/odoo/addons/stock/models/stock_move.py", line 554, in check_recompute_pack_op
    pickings_partial.do_prepare_partial()
  File "/usr/lib/python2.7/site-packages/odoo/addons/stock/models/stock_picking.py", line 616, in do_prepare_partial
    for vals in picking._prepare_pack_ops(picking_quants, forced_qties):
  File "/usr/lib/python2.7/site-packages/odoo/addons/stock/models/stock_picking.py", line 513, in _prepare_pack_ops
    (product, self.location_dest_id.get_putaway_strategy(product) or self.location_dest_id.id) for product in all_products)
  File "/usr/lib/python2.7/site-packages/odoo/addons/stock/models/stock_picking.py", line 513, in <genexpr>
    (product, self.location_dest_id.get_putaway_strategy(product) or self.location_dest_id.id) for product in all_products)
  File "/usr/lib/python2.7/site-packages/odoo/addons/stock/models/stock_location.py", line 106, in get_putaway_strategy
    ('id', '=', self.id)])
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1518, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4221, in _search
    query = self._where_calc(args)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4022, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/usr/lib/python2.7/site-packages/odoo/osv/expression.py", line 1298, in to_sql
    q2 = stack.pop()
IndexError: pop from empty list

>

**Comment by rousseldenis** [comment] 2018-05-08 20:35
@infospa I think I fixed it

**Comment by infospa** [comment] 2018-05-09 13:15
Ok yes you have fixed.

Unfortunately, the destination location changes automatically again with the Put Away Locations
I have a structure
WH
     STOCK
          FLOWER
               Rack1
               Rack2
               Rack3
Put Away Strategy is in STOCK
Product1 is in Rack1
If i move Product1 in FLOWER when I automatically reserve the destination it becomes Rack1.
If I disable Put Away Strategy everything works

**Comment by rousseldenis** [comment] 2018-05-09 13:29
@infospa Is your 'FLOWER' location under STOCK ?

If the answer is yes and if putaway strategy is on STOCK to go to Rack1, this is normal. That's the expected behaviour.

**Comment by infospa** [comment] 2018-05-09 13:38
Sorry but I'm doing an internal movement, I can understand that putaway strategy behaves so in arrive but if I want to move internally 30 different products I have to change 30 times the destination.
Sorry Sorry My english!

**Comment by rousseldenis** [comment] 2018-05-09 13:43
@infospa Maybe you need an explanation on how putaway strategies work. Please look at Odoo documentation. http://www.odoo.com/documentation/user/10.0/inventory/routes/strategies/putaway.html

Indeed, the original bug seems to be solved. 

Do you agree to close this ?

**Comment by infospa** [comment] 2018-05-09 13:47
You close!
Thank You !

You were very kind!

**Closed as completed** 2018-05-09 14:00 UTC
