### ISSUE TITLE
[13.0] Modules don't show up in apps.odoo.com

### ISSUE THREAD

**Issue by yk2kus** [OCA/stock-logistics-warehouse#831] opened 2020-01-14 16:15 UTC
Can you please add the module to apps for V13?

https://www.odoo.com/apps/modules/12.0/stock_available_unreserved/

**Comment by LoisRForgeFlow** [comment] 2020-01-15 12:46
I can confirm that no v13 module of this repo is at the odoo app store.

**Comment by pedrobaeza** [comment] 2020-01-15 12:50
Any 13.0 branch is published on Odoo Apps Store, but you can find all in https://odoo-community.org/shop

**Comment by pedrobaeza** [comment] 2020-01-15 12:50
@simahawk maybe you can take this task that I was to do previously? Tell me and I'll send you some information for automation.

**Comment by rousseldenis** [comment] 2020-01-15 12:55
@LoisRForgeFlow 

![image](https://user-images.githubusercontent.com/19529533/72435557-9f962880-379e-11ea-9348-bf48359d0602.png)

**Comment by pedrobaeza** [comment] 2020-01-15 12:55
~~Somebody has registered it by its own...~~

EDIT: Seen that it was OCA's app "store"

**Comment by rousseldenis** [comment] 2020-01-15 12:55
Ah yes, on Odoo

**Comment by rousseldenis** [comment] 2020-01-15 12:58
Apparently, they changed the way product are displayed for 13.0.

![image](https://user-images.githubusercontent.com/19529533/72435742-1cc19d80-379f-11ea-8a1f-fdff1f6f1190.png)

**Comment by simahawk** [comment] 2020-01-15 13:36
@pedrobaeza is it documented anywhere?

**Comment by pedrobaeza** [comment] 2020-01-15 13:42
Nop. I just have an email from Odoo's app store detailing some REST API services that can help for this that I can forward to you. We did an attempt through scrapping in the past that is in https://github.com/OCA/maintainer-tools/pull/409

**Comment by simahawk** [comment] 2020-01-15 13:58
@pedrobaeza if does not contain any sensitive data you could post it on that issue.
Otherwise, fwd it to me pls.

**Comment by pedrobaeza** [comment] 2020-01-15 14:01
No, here it is:

------------
Here a the main 2 route that should interest you:

route:  [/apps/scan_repo]
args: INT repo_id {mandatory}
returns: None
use: will force a scan of the repository
ex:
var repo_id=2
ajax.jsonRpc('/apps/scan_repo', 'call', {
                    'repo_id': repo_id
                }).done(function(){
                    // your code
                });

route:  [/apps/upload_repo]
args:  STR url 
           INT repo_id {mandatory}
returns: error on fail, nothing on success
use: will either create a new repo or update url of existing one when repo_id is provided
example:ajax.jsonRpc('/apps/upload_repo', 'call', {
                    'url': url,
                    'repo_id': repo_id
                }).done(function(error){
                    if (error) {
                        // log this somewhere to rescan
                    } else {
                        // next();
                    }
                });

the repo_id value can be scrapped from the dashboard/repos with a query like so : 
_.map($("input[name='repo_id']").toArray(),function (i) {return i.value});

Both routes need you to be connected but I guess this could be easily adapted in a small JS script or at least reduce drastically the complexity of your tool.

--------------

**Comment by simahawk** [comment] 2020-01-18 09:48
> the repo_id value can be scrapped from the dashboard/repos

which dashboard? There's no way to get a list of existing repo via specific endpoint?

BTW to me is insane that we have to do all this work to make them index community repos.
IMO we should provide the list of repos and THEY should fetch and scan them all.
We could expose the list via odoo-community.org and they can have a cron to retrieve the full list every X days.
Since we already have our apps store, this should be quite easy.

As far as you know/remember, anything like this had been already discussed w/ them?

**Comment by pedrobaeza** [comment] 2020-01-19 16:34
No, it hasn't be discussed, but not sure if they want to add GitHub queries to know new branches and put filters for that for avoiding temp branches.

**Comment by simahawk** [comment] 2020-01-20 12:25
if we expose an endpoint w/ the results ready to be used they won't need to scan github repos. That's the idea.

**Comment by yk2kus** [comment] 2020-02-12 17:17
so are we going to have OCA modules on apps.odoo.com or not anymore?

**Comment by simahawk** [comment] 2020-02-19 07:39
@yk2kus it's online now :tada: 
If you spot other modules/repo missing, please, let us know.

**Comment by rousseldenis** [comment] 2020-02-19 08:54
![image](https://user-images.githubusercontent.com/19529533/74817790-cdbadb00-52fd-11ea-9c07-36640d07879a.png)

Closing

**Closed as completed by rousseldenis** 2020-02-19 08:54 UTC
